### ISSUE TITLE
Kyocero Hydro XTRM

### ISSUE THREAD

**Issue by hroark13** [djrbliss/loki#71]
Hi Bliss, I was wondering if you could add support for Kyocera Hydro XTRM
This is a different phone than the Kyocera Hydro that you looked at before. I have looked at the aboot and it does not seem to be patched against Loki. It does requires a signed recovery, when I flash a repacked recovery, and try to boot into recovery, I get a message saying "Error 101: The phone has been flashed with unauthorized software & is locked. Visit metropcs.com/securelock for more information". I do not see any of these words/strings in the aboot file for some reason.

Here is a link to a zip with the aboot, boot, and recovery partitions
https://www.mediafire.com/?szg09zoh11izb8c

I understand that you are busy, and may not have time to look into this, and that is cool, I really appreciate all that you do for the Android Community

hK

**Comment by djrbliss** [comment]
Kyocera devices can't be easily supported. Closing for now.
