### ISSUE TITLE
Kyocera KYL21 support

### ISSUE THREAD

**Issue by supersonicninja** [djrbliss/loki#86]
Hi.

Thanks for adding support for Japanese phone LG G2 L-01F back then.

I have rooted the Japanese phone Kyocera KYL21 and disabled mmc write lock, now all I need is to bypass the signature check of the boot and recovery.

Here is the aboot.
http://www.mediafire.com/download/epubzcuc82tlbuz/aboot_kyl21

The loki_tool find function did not find the values automatically.
The aboot base seems to be same as the LG and Samsung (0x88efffd8).
I think that this aboot has some new pattern which do not match with the current 6 patterns defined in the loki.h.

Please look the aboot to add support for this phone, or tell me how to find the pattern.

**Comment by supersonicninja** [comment]
https://github.com/supersonicninja/lk_kyl21
This is the little kernel for this model.
KYL21 is a old msm8960 ics phone. I hope it is not patched yet for loki method.

**Comment by supersonicninja** [comment]
My findings so far.

The loki once have had a support for a kyocera phone.
https://github.com/djrbliss/loki/commit/6516d870da283c351841f8703ba74cf92eb7b48f
The pattern of kyocera hydro  "\x2d\xe9\xf0\x4f\x82\x46\x8d\xb0" appears in the kyl21 aboot at 0x6888.
0x6888 added with the aboot base 0x88efffd8 is 0x88f06860, which should be the check_sig value.

hiikezoe made a fork of loki that has some kyocera phones support including newer one than kyl21. 
https://github.com/hiikezoe/loki
The hdr value of all kyocera phones are 0x88f581a4 in this fork.

	{
		.vendor = "DoCoMo",
		.device = "Kyocera DIGNO S KYL21",
		.build = "021.0.3d60",
		.injection_address = 0x88f06860,
		.hdr = 0x88f581a4
		.use_original_page_size = true,
	},

I added above to loki_patch.c for testing.
The pattern "\x2d\xe9\xf0\x4f\x82\x46\x8d\xb0" was also added to the patterns in the original loki, or to the opcodes in the hiikezoe's loki fork. 
Neither worked.

The error code "ERROR: Cannot read boot signature" is at line 400 of the aboot.c source code of the lk. This error is just before the image_verify function at the line 404, which seems to be the same function as the check_sig of the lg aboot.
 "ERROR: Cannot read boot signature" also appears at the 0x205a0 of the kyl21 aboot as a plain text. Adding 0x250a0 and the aboot base 0x88efffd8 results 0x88f20578.
0x88f20578 reversed by little-endian is 78 05 f2 88. This string is found at
0x9154 c8 05 f2 88 78 05 f2 88 a0 2b f3 88
0x9688 14 03 f2 88 78 05 f2 88 a0 2b f3 88
The a0 2b f3 88 which appears at both examples just after the 78 05 f2 88 can be read as 0x88f32ba0 in big-endian.
0x88f32ba0 minus aboot base 0x88efffd8 is 0x32bc8. 0x32bc8 of the kyl21 aboot is the start of the ANDROID_BOOT! which suggests that it is a part of the boot code.

Both 0x88f20578 and the 0x88f32ba0 were tested as the hdr. Neither of them succeeded.

If anyone found a mistake in the above hdr calculation, please point it out.
Maybe the pattern and the resulting check_sig address is wrong. I didn't find any reference to how to find the loki pattern. If someone knows how to find the correct pattern, please tell me.

**Comment by djrbliss** [comment]
I don't believe Kyocera devices can be easily supported, and since I don't have the means to do any testing, I'm closing this issue for now.
