### ISSUE TITLE
Can/will this be modded for Android 5.0.1?

### ISSUE THREAD

**Issue by Deweywsu** [djrbliss/loki#90]
Hi

I noticed in the code that loki (at the time I'm writing this), for the AT&T Samsung Galaxy S4, targets builds JDQ39.I337UCUAMDB or JDQ39.I337UCUAMDL.  Mine has what appears to be a newer LRX22C.I337UCUGOC4 (Android 5.0.1).

I see there haven't been any commits for about half a year.  Is this project still on like Donkey Kong?  If it isn't, I'm afraid I don't have enough knowledge to verify, but if I simply insert my newer build number in the list of acceptable builds for the S4, is there a chance it will work (I know, a shot in the dark), or do I risk bricking?

Thanks for any help
-Dewey

**Comment by djrbliss** [comment]
This project has been dead for years. The vulnerability targeted by Loki was patched ages ago, so this will never work on newer builds.
